/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#556500',
        'primary-container': '#9CB434',
        'primary-fixed': '#d4ee68',
        'primary-fixed-dim': '#b8d24f',
        secondary: '#556500',
        'secondary-container': '#d5ea7c',
        tertiary: '#87409d',
        'tertiary-container': '#da8cef',
        surface: '#fcf9f5',
        'surface-bright': '#fcf9f5',
        'surface-dim': '#dcdad6',
        'surface-container': '#f0edea',
        'surface-container-low': '#f6f3ef',
        'surface-container-high': '#ebe8e4',
        'surface-container-highest': '#e5e2de',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1c1c1a',
        'on-surface-variant': '#454837',
        'on-primary': '#ffffff',
        'on-primary-container': '#374300',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#596903',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#631b7a',
        outline: '#767965',
        'outline-variant': '#c6c8b2',
        'inverse-surface': '#31302e',
        'inverse-on-surface': '#f3f0ec',
        'inverse-primary': '#b8d24f',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        background: '#fcf9f5',
      },
      fontFamily: {
        sans: ['"Be Vietnam Pro"', 'sans-serif'],
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        '2xl': '3rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0 20px 40px rgba(28, 28, 26, 0.06)',
      },
    },
  },
  plugins: [],
};
